EXE = main
TEST = test
OBJS = main.o DFS.o BFS.o pagerank.o betweenness.o
TEST_OBJS = DFS.o BFS.o pagerank.o betweenness.o test.o

CXX = clang++
CXXFLAGS = $(CS225) -std=c++1y -stdlib=libc++ -c -g -O0 -Wall -Wextra -pedantic
LD = clang++
LDFLAGS = -std=c++1y -stdlib=libc++ -lc++abi -lm
OBJS_DIR = .objs


# Custom Clang version enforcement logic:
ccred=$(shell echo -e "\033[0;31m")
ccyellow=$(shell echo -e "\033[0;33m")
ccend=$(shell echo -e "\033[0m")

WARNINGS = -pedantic -Wall -Werror -Wfatal-errors -Wextra -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function

all: $(EXE)

$(EXE): output_msg $(patsubst %.o, $(OBJS_DIR)/%.o, $(OBJS))
	$(LD) $(filter-out $<, $^) $(LDFLAGS) -o $@

main.o: src/main.cpp src/graph.cpp src/graph.h src/dfs.cpp src/dfs.h src/pagerank.cpp src/pagerank.h
	$(CXX) $(CXXFLAGS) src/main.cpp

betweenness.o: src/betweenness.cpp src/betweenness.h src/node.cpp src/node.h src/bfs.cpp src/bfs.h
	$(CXX) $(CXXFLAGS) src/betweenness.cpp

dfs.o: src/dfs.cpp src/dfs.h src/node.cpp src/node.h src/graph.cpp src/graph.h 
	$(CXX) $(CXXFLAGS) src/dfs.cpp

bfs.o: src/bfs.cpp src/bfs.h src/node.cpp src/node.h src/graph.cpp src/graph.h 
	$(CXX) $(CXXFLAGS) src/bfs.cpp

pagerank.o: src/pagerank.cpp src/pagerank.h src/node.cpp src/node.h src/graph.cpp src/graph.h 
	$(CXX) $(CXXFLAGS) src/pagerank.cpp

test: output_msg $(TEST_OBJS)
	$(LD) $(TEST_OBJS) $(LDFLAGS) -o test

tests.o: tests/tests.cpp catch/catch.hpp
	$(CXX) $(CXXFLAGS) tests/tests.cpp

clean:
	rm -rf $(EXE) $(TEST) $(OBJS_DIR) $(CLEAN_RM) *.o *.d